http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
  api-registro:
    host: '*'
    paths: ['/signin','/signin/*']
    methods: ["HEAD","GET","PUT","PATCH","POST","DELETE","OPTIONS"]
  api-autenticacion:
    host: '*'
    paths: ['/auth','/auth/*']
    methods: ["HEAD","GET","PUT","PATCH","POST","DELETE","OPTIONS"]
serviceEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
  service-registro:
    url: 'http://app-registro:3000/signin'
  service-autenticacion:
    url: 'http://app-autenticacion:3000/auth'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  # see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines
  pipeline-registro:
    apiEndpoints:
      - api-registro
    policies:
      - proxy:
        - action: 
            serviceEndpoint: service-registro
            changeOrigin: true
            stripPath: true
      - cors:
          - action:
              origin: ["*"]
              methods: ["HEAD","GET","PUT","PATCH","POST","DELETE","OPTIONS"]
              preflightContinue: true
              optionsSuccessStatus: 204
              maxAge: 600
              allowedHeaders:
                [
                  "Origin, X-Requested-With, Content-Type, Accept, Authorization","options"
                ]

  pipeline-autenticacion:
    apiEndpoints:
      - api-autenticacion
    policies:
      - proxy:
        - action: 
            serviceEndpoint: service-autenticacion
            changeOrigin: true
            stripPath: true
      - cors:
          - action:
              origin: ["*"]
              methods: ["HEAD","GET","PUT","PATCH","POST","DELETE","OPTIONS"]
              preflightContinue: true
              optionsSuccessStatus: 204
              maxAge: 600
              allowedHeaders:
                [
                  "Origin, X-Requested-With, Content-Type, Accept, Authorization","options"
                ]